version: "3.8"

services:

   controll:
      build: ./controll
      container_name: controll
      ports:
         - 50051:50051 
      restart: unless-stopped
      
   dind1:
      build: ./image
      container_name: dind1
      privileged: true
      mem_limit: 512m
      mem_reservation: 512m
      cpus: "0.50"
      ports:
        - 50050:50051 
      volumes:
         - dind1-data:/var/lib/docker
      environment:
        - CONTAINER_ADDRESS=dind1:50051
      restart: unless-stopped
      
   dind2:
      build: ./image
      container_name: dind2
      privileged: true
      mem_limit: 512m
      mem_reservation: 512m
      cpus: "0.50"
      ports:
        - 50052:50051 
      volumes:
         - dind2-data:/var/lib/docker
      environment:
        - CONTAINER_ADDRESS=dind2:50051
      restart: unless-stopped

   redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    command: redis-server --appendonly yes

volumes:
  redis_data:
  dind1-data:
  dind2-data: