// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/status_receiver/status_receiver.proto

package status_receiver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	CpuUsage      string                 `protobuf:"bytes,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsage      string                 `protobuf:"bytes,3,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	RunningImages []*RunningImage        `protobuf:"bytes,4,rep,name=running_images,json=runningImages,proto3" json:"running_images,omitempty"`
	CpuTotal      string                 `protobuf:"bytes,5,opt,name=cpu_total,json=cpuTotal,proto3" json:"cpu_total,omitempty"`
	RamTotal      string                 `protobuf:"bytes,6,opt,name=ram_total,json=ramTotal,proto3" json:"ram_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageStatus) Reset() {
	*x = ImageStatus{}
	mi := &file_proto_status_receiver_status_receiver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageStatus) ProtoMessage() {}

func (x *ImageStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_status_receiver_status_receiver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageStatus.ProtoReflect.Descriptor instead.
func (*ImageStatus) Descriptor() ([]byte, []int) {
	return file_proto_status_receiver_status_receiver_proto_rawDescGZIP(), []int{0}
}

func (x *ImageStatus) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *ImageStatus) GetCpuUsage() string {
	if x != nil {
		return x.CpuUsage
	}
	return ""
}

func (x *ImageStatus) GetRamUsage() string {
	if x != nil {
		return x.RamUsage
	}
	return ""
}

func (x *ImageStatus) GetRunningImages() []*RunningImage {
	if x != nil {
		return x.RunningImages
	}
	return nil
}

func (x *ImageStatus) GetCpuTotal() string {
	if x != nil {
		return x.CpuTotal
	}
	return ""
}

func (x *ImageStatus) GetRamTotal() string {
	if x != nil {
		return x.RamTotal
	}
	return ""
}

type RunningImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	CpuUsage      string                 `protobuf:"bytes,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsage      string                 `protobuf:"bytes,3,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	CpuTotal      string                 `protobuf:"bytes,4,opt,name=cpu_total,json=cpuTotal,proto3" json:"cpu_total,omitempty"`
	RamTotal      string                 `protobuf:"bytes,5,opt,name=ram_total,json=ramTotal,proto3" json:"ram_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunningImage) Reset() {
	*x = RunningImage{}
	mi := &file_proto_status_receiver_status_receiver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningImage) ProtoMessage() {}

func (x *RunningImage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_status_receiver_status_receiver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningImage.ProtoReflect.Descriptor instead.
func (*RunningImage) Descriptor() ([]byte, []int) {
	return file_proto_status_receiver_status_receiver_proto_rawDescGZIP(), []int{1}
}

func (x *RunningImage) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *RunningImage) GetCpuUsage() string {
	if x != nil {
		return x.CpuUsage
	}
	return ""
}

func (x *RunningImage) GetRamUsage() string {
	if x != nil {
		return x.RamUsage
	}
	return ""
}

func (x *RunningImage) GetCpuTotal() string {
	if x != nil {
		return x.CpuTotal
	}
	return ""
}

func (x *RunningImage) GetRamTotal() string {
	if x != nil {
		return x.RamTotal
	}
	return ""
}

var File_proto_status_receiver_status_receiver_proto protoreflect.FileDescriptor

const file_proto_status_receiver_status_receiver_proto_rawDesc = "" +
	"\n" +
	"+proto/status_receiver/status_receiver.proto\x12\x15proto.status_receiver\x1a\x1bgoogle/protobuf/empty.proto\"\xec\x01\n" +
	"\vImageStatus\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\tR\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x03 \x01(\tR\bramUsage\x12J\n" +
	"\x0erunning_images\x18\x04 \x03(\v2#.proto.status_receiver.RunningImageR\rrunningImages\x12\x1b\n" +
	"\tcpu_total\x18\x05 \x01(\tR\bcpuTotal\x12\x1b\n" +
	"\tram_total\x18\x06 \x01(\tR\bramTotal\"\xa1\x01\n" +
	"\fRunningImage\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\tR\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x03 \x01(\tR\bramUsage\x12\x1b\n" +
	"\tcpu_total\x18\x04 \x01(\tR\bcpuTotal\x12\x1b\n" +
	"\tram_total\x18\x05 \x01(\tR\bramTotal2b\n" +
	"\x15StatusReceiverService\x12I\n" +
	"\vShareStatus\x12\".proto.status_receiver.ImageStatus\x1a\x16.google.protobuf.EmptyB4Z2github.com/coigo/micro-cloud/proto/status_receiverb\x06proto3"

var (
	file_proto_status_receiver_status_receiver_proto_rawDescOnce sync.Once
	file_proto_status_receiver_status_receiver_proto_rawDescData []byte
)

func file_proto_status_receiver_status_receiver_proto_rawDescGZIP() []byte {
	file_proto_status_receiver_status_receiver_proto_rawDescOnce.Do(func() {
		file_proto_status_receiver_status_receiver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_status_receiver_status_receiver_proto_rawDesc), len(file_proto_status_receiver_status_receiver_proto_rawDesc)))
	})
	return file_proto_status_receiver_status_receiver_proto_rawDescData
}

var file_proto_status_receiver_status_receiver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_status_receiver_status_receiver_proto_goTypes = []any{
	(*ImageStatus)(nil),   // 0: proto.status_receiver.ImageStatus
	(*RunningImage)(nil),  // 1: proto.status_receiver.RunningImage
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_proto_status_receiver_status_receiver_proto_depIdxs = []int32{
	1, // 0: proto.status_receiver.ImageStatus.running_images:type_name -> proto.status_receiver.RunningImage
	0, // 1: proto.status_receiver.StatusReceiverService.ShareStatus:input_type -> proto.status_receiver.ImageStatus
	2, // 2: proto.status_receiver.StatusReceiverService.ShareStatus:output_type -> google.protobuf.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_status_receiver_status_receiver_proto_init() }
func file_proto_status_receiver_status_receiver_proto_init() {
	if File_proto_status_receiver_status_receiver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_status_receiver_status_receiver_proto_rawDesc), len(file_proto_status_receiver_status_receiver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_status_receiver_status_receiver_proto_goTypes,
		DependencyIndexes: file_proto_status_receiver_status_receiver_proto_depIdxs,
		MessageInfos:      file_proto_status_receiver_status_receiver_proto_msgTypes,
	}.Build()
	File_proto_status_receiver_status_receiver_proto = out.File
	file_proto_status_receiver_status_receiver_proto_goTypes = nil
	file_proto_status_receiver_status_receiver_proto_depIdxs = nil
}
