// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/status_receiver/status_receiver.proto

package status_receiver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatusReceiverService_ShareStatus_FullMethodName = "/proto.status_receiver.StatusReceiverService/ShareStatus"
)

// StatusReceiverServiceClient is the client API for StatusReceiverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.


// StatusReceiverServiceServer is the server API for StatusReceiverService service.
// All implementations must embed UnimplementedStatusReceiverServiceServer
// for forward compatibility.
type StatusReceiverServiceServer interface {
	ShareStatus(context.Context, *ImageStatus) (*emptypb.Empty, error)
	mustEmbedUnimplementedStatusReceiverServiceServer()
}

// UnimplementedStatusReceiverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatusReceiverServiceServer struct{}

func (UnimplementedStatusReceiverServiceServer) ShareStatus(context.Context, *ImageStatus) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ShareStatus not implemented")
}
func (UnimplementedStatusReceiverServiceServer) mustEmbedUnimplementedStatusReceiverServiceServer() {}
func (UnimplementedStatusReceiverServiceServer) testEmbeddedByValue()                               {}

// UnsafeStatusReceiverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatusReceiverServiceServer will
// result in compilation errors.
type UnsafeStatusReceiverServiceServer interface {
	mustEmbedUnimplementedStatusReceiverServiceServer()
}

func RegisterStatusReceiverServiceServer(s grpc.ServiceRegistrar, srv StatusReceiverServiceServer) {
	// If the following call panics, it indicates UnimplementedStatusReceiverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatusReceiverService_ServiceDesc, srv)
}

func _StatusReceiverService_ShareStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusReceiverServiceServer).ShareStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatusReceiverService_ShareStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusReceiverServiceServer).ShareStatus(ctx, req.(*ImageStatus))
	}
	return interceptor(ctx, in, info, handler)
}

// StatusReceiverService_ServiceDesc is the grpc.ServiceDesc for StatusReceiverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatusReceiverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.status_receiver.StatusReceiverService",
	HandlerType: (*StatusReceiverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShareStatus",
			Handler:    _StatusReceiverService_ShareStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/status_receiver/status_receiver.proto",
}
