// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/command_dispatcher/command_dispatcher.proto

package command_dispatcher

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommandDispatcherService_CreateCommand_FullMethodName = "/proto.command_dispatcher.CommandDispatcherService/CreateCommand"
	CommandDispatcherService_DownCommand_FullMethodName   = "/proto.command_dispatcher.CommandDispatcherService/DownCommand"
)

// CommandDispatcherServiceClient is the client API for CommandDispatcherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommandDispatcherServiceClient interface {
	CreateCommand(ctx context.Context, in *CreateCommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	DownCommand(ctx context.Context, in *DownCommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
}

type commandDispatcherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandDispatcherServiceClient(cc grpc.ClientConnInterface) CommandDispatcherServiceClient {
	return &commandDispatcherServiceClient{cc}
}

func (c *commandDispatcherServiceClient) CreateCommand(ctx context.Context, in *CreateCommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, CommandDispatcherService_CreateCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandDispatcherServiceClient) DownCommand(ctx context.Context, in *DownCommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, CommandDispatcherService_DownCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandDispatcherServiceServer is the server API for CommandDispatcherService service.
// All implementations must embed UnimplementedCommandDispatcherServiceServer
// for forward compatibility.
type CommandDispatcherServiceServer interface {
	CreateCommand(context.Context, *CreateCommandRequest) (*CommandResponse, error)
	DownCommand(context.Context, *DownCommandRequest) (*CommandResponse, error)
	mustEmbedUnimplementedCommandDispatcherServiceServer()
}

// UnimplementedCommandDispatcherServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommandDispatcherServiceServer struct{}

func (UnimplementedCommandDispatcherServiceServer) CreateCommand(context.Context, *CreateCommandRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCommand not implemented")
}
func (UnimplementedCommandDispatcherServiceServer) DownCommand(context.Context, *DownCommandRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownCommand not implemented")
}
func (UnimplementedCommandDispatcherServiceServer) mustEmbedUnimplementedCommandDispatcherServiceServer() {
}
func (UnimplementedCommandDispatcherServiceServer) testEmbeddedByValue() {}

// UnsafeCommandDispatcherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandDispatcherServiceServer will
// result in compilation errors.
type UnsafeCommandDispatcherServiceServer interface {
	mustEmbedUnimplementedCommandDispatcherServiceServer()
}

func RegisterCommandDispatcherServiceServer(s grpc.ServiceRegistrar, srv CommandDispatcherServiceServer) {
	// If the following call panics, it indicates UnimplementedCommandDispatcherServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommandDispatcherService_ServiceDesc, srv)
}

func _CommandDispatcherService_CreateCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandDispatcherServiceServer).CreateCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandDispatcherService_CreateCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandDispatcherServiceServer).CreateCommand(ctx, req.(*CreateCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandDispatcherService_DownCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandDispatcherServiceServer).DownCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandDispatcherService_DownCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandDispatcherServiceServer).DownCommand(ctx, req.(*DownCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommandDispatcherService_ServiceDesc is the grpc.ServiceDesc for CommandDispatcherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommandDispatcherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.command_dispatcher.CommandDispatcherService",
	HandlerType: (*CommandDispatcherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCommand",
			Handler:    _CommandDispatcherService_CreateCommand_Handler,
		},
		{
			MethodName: "DownCommand",
			Handler:    _CommandDispatcherService_DownCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/command_dispatcher/command_dispatcher.proto",
}
