// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/command_dispatcher/command_dispatcher.proto

package command_dispatcher

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerSize int32

const (
	ContainerSize_SMALL  ContainerSize = 0
	ContainerSize_MEDIUM ContainerSize = 1
	ContainerSize_LARGE  ContainerSize = 2
)

// Enum value maps for ContainerSize.
var (
	ContainerSize_name = map[int32]string{
		0: "SMALL",
		1: "MEDIUM",
		2: "LARGE",
	}
	ContainerSize_value = map[string]int32{
		"SMALL":  0,
		"MEDIUM": 1,
		"LARGE":  2,
	}
)

func (x ContainerSize) Enum() *ContainerSize {
	p := new(ContainerSize)
	*p = x
	return p
}

func (x ContainerSize) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerSize) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_command_dispatcher_command_dispatcher_proto_enumTypes[0].Descriptor()
}

func (ContainerSize) Type() protoreflect.EnumType {
	return &file_proto_command_dispatcher_command_dispatcher_proto_enumTypes[0]
}

func (x ContainerSize) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerSize.Descriptor instead.
func (ContainerSize) EnumDescriptor() ([]byte, []int) {
	return file_proto_command_dispatcher_command_dispatcher_proto_rawDescGZIP(), []int{0}
}

type CreateCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerSize ContainerSize          `protobuf:"varint,1,opt,name=container_size,json=containerSize,proto3,enum=proto.command_dispatcher.ContainerSize" json:"container_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommandRequest) Reset() {
	*x = CreateCommandRequest{}
	mi := &file_proto_command_dispatcher_command_dispatcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommandRequest) ProtoMessage() {}

func (x *CreateCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_dispatcher_command_dispatcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommandRequest.ProtoReflect.Descriptor instead.
func (*CreateCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_command_dispatcher_command_dispatcher_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCommandRequest) GetContainerSize() ContainerSize {
	if x != nil {
		return x.ContainerSize
	}
	return ContainerSize_SMALL
}

type DownCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownCommandRequest) Reset() {
	*x = DownCommandRequest{}
	mi := &file_proto_command_dispatcher_command_dispatcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownCommandRequest) ProtoMessage() {}

func (x *DownCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_dispatcher_command_dispatcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownCommandRequest.ProtoReflect.Descriptor instead.
func (*DownCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_command_dispatcher_command_dispatcher_proto_rawDescGZIP(), []int{1}
}

func (x *DownCommandRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_proto_command_dispatcher_command_dispatcher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_dispatcher_command_dispatcher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_command_dispatcher_command_dispatcher_proto_rawDescGZIP(), []int{2}
}

func (x *CommandResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

var File_proto_command_dispatcher_command_dispatcher_proto protoreflect.FileDescriptor

const file_proto_command_dispatcher_command_dispatcher_proto_rawDesc = "" +
	"\n" +
	"1proto/command_dispatcher/command_dispatcher.proto\x12\x18proto.command_dispatcher\"f\n" +
	"\x14CreateCommandRequest\x12N\n" +
	"\x0econtainer_size\x18\x01 \x01(\x0e2'.proto.command_dispatcher.ContainerSizeR\rcontainerSize\"7\n" +
	"\x12DownCommandRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"4\n" +
	"\x0fCommandResponse\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId*1\n" +
	"\rContainerSize\x12\t\n" +
	"\x05SMALL\x10\x00\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x01\x12\t\n" +
	"\x05LARGE\x10\x022\xee\x01\n" +
	"\x18CommandDispatcherService\x12j\n" +
	"\rCreateCommand\x12..proto.command_dispatcher.CreateCommandRequest\x1a).proto.command_dispatcher.CommandResponse\x12f\n" +
	"\vDownCommand\x12,.proto.command_dispatcher.DownCommandRequest\x1a).proto.command_dispatcher.CommandResponseB7Z5github.com/coigo/micro-cloud/proto/command_dispatcherb\x06proto3"

var (
	file_proto_command_dispatcher_command_dispatcher_proto_rawDescOnce sync.Once
	file_proto_command_dispatcher_command_dispatcher_proto_rawDescData []byte
)

func file_proto_command_dispatcher_command_dispatcher_proto_rawDescGZIP() []byte {
	file_proto_command_dispatcher_command_dispatcher_proto_rawDescOnce.Do(func() {
		file_proto_command_dispatcher_command_dispatcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_command_dispatcher_command_dispatcher_proto_rawDesc), len(file_proto_command_dispatcher_command_dispatcher_proto_rawDesc)))
	})
	return file_proto_command_dispatcher_command_dispatcher_proto_rawDescData
}

var file_proto_command_dispatcher_command_dispatcher_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_command_dispatcher_command_dispatcher_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_command_dispatcher_command_dispatcher_proto_goTypes = []any{
	(ContainerSize)(0),           // 0: proto.command_dispatcher.ContainerSize
	(*CreateCommandRequest)(nil), // 1: proto.command_dispatcher.CreateCommandRequest
	(*DownCommandRequest)(nil),   // 2: proto.command_dispatcher.DownCommandRequest
	(*CommandResponse)(nil),      // 3: proto.command_dispatcher.CommandResponse
}
var file_proto_command_dispatcher_command_dispatcher_proto_depIdxs = []int32{
	0, // 0: proto.command_dispatcher.CreateCommandRequest.container_size:type_name -> proto.command_dispatcher.ContainerSize
	1, // 1: proto.command_dispatcher.CommandDispatcherService.CreateCommand:input_type -> proto.command_dispatcher.CreateCommandRequest
	2, // 2: proto.command_dispatcher.CommandDispatcherService.DownCommand:input_type -> proto.command_dispatcher.DownCommandRequest
	3, // 3: proto.command_dispatcher.CommandDispatcherService.CreateCommand:output_type -> proto.command_dispatcher.CommandResponse
	3, // 4: proto.command_dispatcher.CommandDispatcherService.DownCommand:output_type -> proto.command_dispatcher.CommandResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_command_dispatcher_command_dispatcher_proto_init() }
func file_proto_command_dispatcher_command_dispatcher_proto_init() {
	if File_proto_command_dispatcher_command_dispatcher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_command_dispatcher_command_dispatcher_proto_rawDesc), len(file_proto_command_dispatcher_command_dispatcher_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_command_dispatcher_command_dispatcher_proto_goTypes,
		DependencyIndexes: file_proto_command_dispatcher_command_dispatcher_proto_depIdxs,
		EnumInfos:         file_proto_command_dispatcher_command_dispatcher_proto_enumTypes,
		MessageInfos:      file_proto_command_dispatcher_command_dispatcher_proto_msgTypes,
	}.Build()
	File_proto_command_dispatcher_command_dispatcher_proto = out.File
	file_proto_command_dispatcher_command_dispatcher_proto_goTypes = nil
	file_proto_command_dispatcher_command_dispatcher_proto_depIdxs = nil
}
